This repository hosts some guix package definitions that yet to be upstreamed
or simply can not be upstreamed.

If any of the package is upstreamed, I will try to removed it here. But
sometimes it's more convenient for me to keep some of them local, so that I can
work with it any time I want. :)

Some definitions are ported from:
https://gitlab.com/genenetwork/guix-bioinformatics.
Copyright notice is included.

* Status

** Cuda

   Is not fully work yet, at least not in real pure environment. It seems that
   some dynamic load path are messed up in the binaries. If I omit testing in
   wrap-program, cuda builds alright, and *nvcc* *CAN* be used on *host system*.
   However, it can not be invoked inside the store environment, which means you
   *CAN'T* package other software having cuda as dependency, but you *CAN* use
   it with `guix environment` during development process.

   The failure is weird, no error message is emitted, nvcc just failed with
   non-zero return code.
   One possible explanation might be the /dev file is invisible inside store
   environment, as mentioned in the link at following OpenCL section.

   Other than that, I am still trying to get all those dynamic load path right.

   How come the definition from nix looks so innocently simple anyway?

** OpenCL

   Currently *clinfo* can display information about *pocl* and *beignet*.
   Anything other than that might not be working.

   I tried to call OpenCL functions in `guix environment --pure`, but getting
   cl device info results in segmentation fault. Please note that *clinfo* does
   the same thing but it didn't get into any trouble.

   Testing for OpenCL implementation might not be doable inside the store
   environment, as mentioned in:
   https://lists.gnu.org/archive/html/guix-devel/2018-04/msg00293.html

   + Various OpenCL headers.
   + ocl-icd
   + clinfo
   + ClMath: clBLAS, clFFT
   + boost_compute

*** Implementations, WIP:

   + beignet
   + pocl

** Arrayfire

   The old cpu version is working. I can't get any further due to broken cuda.

** Others
   + libffm
   + opencv (from guix devel list)
   + lightgbm
   + vowpal-wabbit
   + xtensor
   + pybind11
   + xgboost
   + python-xgboost

Many libraries are packaged as dependencies, just grep "define-public".


* Upstreamed
   + bear
   + unittest-cpp
   + qBittorrent
   + python-autograd
   + amule
   + python-yapf
   + python-parso
   + python-glob2

#  LocalWords:  upstreamed LocalWords nvcc OpenCL Cuda cuda dev pocl
#  LocalWords:  clinfo guix icd clFFT beignet qBittorrent cpp WIP
#  LocalWords:  autograd Arrayfire libffm opencv amule lightgbm parso
#  LocalWords:  pybind yapf
