This repository hosts some guix package definitions that yet to be upstreamed
or simply can not be upstreamed.

If any of the package is upstreamed, it will be removed here.

Some definitions are ported from:
https://gitlab.com/genenetwork/guix-bioinformatics.
Copyright notice is included.

* Status
** Cuda
   Doesn't work yet, at least not in real pure environment. It seems that some
   dynamic load path are messed up in the binaries. If I omit testing in
   wrap-program, cuda builds alright, and /nvcc/ *can* be used on *host system*.
   However, it can not be invoked inside the store environment, which means you
   *can't* package other software having cuda as dependency, but you *can* use
   it with `guix environment` during development process.
   The failure is weird, no error message is emitted, nvcc just failed with
   non-zero return code. I am still trying to get all those dynamic load path
   right. How come the definition from nix looks so innocently simple anyway?

** OpenCL
   + OpenCL headers.
   + ocl-icd
   + ClMath: clBLAS, clFFT
   + boost_compute
*** Tests failed:
   + beignet
   + pocl

** Arrayfire
   The old cpu version is working. I can't get any further due to broken cuda.

** Others
   + amule
   + python-autograd
     
Many libraries are packaged as dependencies, just grep "define-public".


* Upstreamed
   + bear
   + unittest-cpp
   + qBittorrent

#  LocalWords:  upstreamed LocalWords
