This repository hosts some guix package definitions that yet to be upstreamed
or simply can not be upstreamed.

If any of the package is upstreamed, I will try to mention it in
`upstreamed.org` and remove it from the source tree. But sometimes it's more
convenient for me to keep some of them local, so that I can work with it any
time I want. :)

I want to maintain this repository, but with my very limited resource, this
doesn't seem possible.  If you want to help, please make an issue or PR. :)

Some definitions are ported from:
https://gitlab.com/genenetwork/guix-bioinformatics.
Copyright notice is included.

* Channel
You can use the following definition as additional, be aware that I'm not
constantly following up the upstream, if you found some packages not building,
please let me know.
#+BEGIN_SRC scheme
(cons
 (channel
  (name 'fis)
  (url "https://github.com/trivialfis/guixpkgs.git")
  (branch "master"))
 %default-channels)
#+END_SRC

* Status
** OpenCL

   Testing for OpenCL implementation might not be doable inside the store
   environment, as mentioned in:
   https://lists.gnu.org/archive/html/guix-devel/2018-04/msg00293.html

   + ClMath: clBLAS, clFFT
   + boost-compute

** Arrayfire

   The old cpu version is working. I can't get any further due to broken cuda.

** Others
   + redsocks
   + cquery
   + ccls
   + libffm
   + xgboost
   + python-xgboost
   + python-twython

Many libraries are packaged as dependencies, just grep "define-public".
